# app.py — Streamlit chat UI for the Research Paper RAG
# Run with:  python -m streamlit run app.py --server.fileWatcherType none

import streamlit as st
from langchain_ollama import ChatOllama
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableLambda

from retriever import build_retriever
from chain import CITATION_PROMPT, format_docs_with_citations

# ── Page config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Research Paper Q&A",
    layout="centered",
)

# ── Header ────────────────────────────────────────────────────────────────────

st.title("Research Paper Q&A")
st.caption(
    "Production RAG — hybrid retrieval (BM25 + ChromaDB) · "
    "cross-encoder reranking · citation enforcement · multi-LLM"
)
st.divider()

# ── Sidebar ───────────────────────────────────────────────────────────────────

AVAILABLE_MODELS = ["llama3.2", "mistral", "gemma3:1b"]

with st.sidebar:
    st.header("Pipeline")
    st.markdown(
        """
        **Indexing**
        - Source: PDF files in `papers/`
        - Embeddings: `all-mpnet-base-v2`
        - Vector store: ChromaDB (persistent)
        - Keyword store: BM25

        **Querying**
        - Hybrid retrieval (RRF fusion)
        - Cross-encoder reranking
        - Top 5 chunks with relevance scores
        - Citation-enforced prompt
        """
    )
    st.divider()

    selected_model = st.selectbox(
        "LLM Model",
        AVAILABLE_MODELS,
        index=0,
        help="Switch between locally available Ollama models",
    )

    st.divider()
    if st.button("Clear conversation"):
        st.session_state.messages = []
        st.rerun()

# ── Load retriever once (heavy — shared across all models) ────────────────────

@st.cache_resource(show_spinner="Loading retriever models — please wait...")
def load_retriever():
    return build_retriever()

retriever = load_retriever()

# ── Query rewriter ────────────────────────────────────────────────────────────

REWRITE_PROMPT = """You are a query rewriter for a research paper Q&A system.
Rewrite the user's question using precise academic terminology so it better matches content in research papers.
Only return the rewritten question — no explanation, no preamble.

User question: {question}
Rewritten question:"""

def rewrite_query(question: str, model_name: str) -> str:
    llm = ChatOllama(model=model_name, temperature=0)
    prompt = REWRITE_PROMPT.format(question=question)
    rewritten = llm.invoke(prompt).content.strip()
    return rewritten

# ── Build chain for selected model (cached per model name) ────────────────────

@st.cache_resource(show_spinner="Loading LLM...")
def load_chain(model_name: str):
    llm = ChatOllama(model=model_name, temperature=0)
    chain = (
        {
            "context":  retriever | RunnableLambda(format_docs_with_citations),
            "question": RunnablePassthrough(),
        }
        | CITATION_PROMPT
        | llm
        | StrOutputParser()
    )
    return chain

chain = load_chain(selected_model)

# ── Chat state ────────────────────────────────────────────────────────────────

if "messages" not in st.session_state:
    st.session_state.messages = []

# Show which model is active
st.info(f"Active model: **{selected_model}**")

# Render conversation history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg["role"] == "assistant":
            if "model" in msg:
                st.caption(f"Generated by: `{msg['model']}`")
            if "sources" in msg:
                with st.expander("Retrieved sources"):
                    for i, s in enumerate(msg["sources"], 1):
                        score_label = f"  —  relevance: `{s['relevance_score']:.4f}`" if s.get("relevance_score") is not None else ""
                        st.caption(f"**[{i}]** {s['url']}{score_label}")
                        st.markdown(f"> {s['snippet']}...")
                        if i < len(msg["sources"]):
                            st.divider()

# ── Chat input ────────────────────────────────────────────────────────────────

if question := st.chat_input("Ask anything about the research paper..."):

    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        with st.spinner(f"Retrieving and generating with {selected_model}..."):
            rewritten = rewrite_query(question, selected_model)
            retrieved_docs = retriever.invoke(rewritten)
            answer = chain.invoke(question)

        # ── Terminal logging ──────────────────────────────────────────────
        print("\n" + "="*60)
        print(f"QUESTION  : {question.encode('ascii', errors='replace').decode('ascii')}")
        print(f"REWRITTEN : {rewritten.encode('ascii', errors='replace').decode('ascii')}")
        print(f"MODEL     : {selected_model}")
        print("-"*60)
        for i, doc in enumerate(retrieved_docs, 1):
            score = doc.metadata.get("relevance_score", "n/a")
            print(f"[{i}] score={score}  source={doc.metadata.get('source','unknown')}")
            print(f"    {doc.page_content.strip()[:200].encode('ascii', errors='replace').decode('ascii')}")
        print("-"*60)
        print(f"ANSWER   : {answer.encode('ascii', errors='replace').decode('ascii')}")
        print("="*60 + "\n")

        st.markdown(answer)
        st.caption(f"Generated by: `{selected_model}` · searched as: *{rewritten}*")

        sources = []
        with st.expander("Retrieved sources"):
            for i, doc in enumerate(retrieved_docs, 1):
                url       = doc.metadata.get("source", "unknown")
                snippet   = doc.page_content.strip()[:250]
                relevance = doc.metadata.get("relevance_score")
                sources.append({"url": url, "snippet": snippet, "relevance_score": relevance})

                score_label = f"  —  relevance: `{relevance:.4f}`" if relevance is not None else ""
                st.caption(f"**[{i}]** {url}{score_label}")
                st.markdown(f"> {snippet}...")
                if i < len(retrieved_docs):
                    st.divider()

    st.session_state.messages.append({
        "role":    "assistant",
        "content": answer,
        "model":   selected_model,
        "sources": sources,
    })
