# app.py — Streamlit chat UI for the Research Paper RAG
# Run with:  python -m streamlit run app.py --server.fileWatcherType none

import streamlit as st
from langchain_ollama import ChatOllama
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableLambda

from retriever import build_retriever
from chain import CITATION_PROMPT, format_docs_with_citations
from config import OLLAMA_HOST, AVAILABLE_MODELS

# AGENTIC AI — import the agent entry point from agent.py
# run_agent() replaces chain.invoke() when the user picks "Agentic Mode"
from agent import run_agent

# ── Page config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Research Paper Q&A",
    layout="centered",
)

# ── Header ────────────────────────────────────────────────────────────────────

st.title("Research Paper Q&A")
st.caption(
    "Production RAG — hybrid retrieval (BM25 + ChromaDB) · "
    "cross-encoder reranking · citation enforcement · multi-LLM"
)
st.divider()

# ── Sidebar ───────────────────────────────────────────────────────────────────

with st.sidebar:
    st.header("Pipeline")
    st.markdown(
        """
        **Indexing**
        - Source: PDF files in `papers/`
        - Embeddings: `all-mpnet-base-v2`
        - Vector store: ChromaDB (persistent)
        - Keyword store: BM25

        **Querying**
        - Hybrid retrieval (RRF fusion)
        - Cross-encoder reranking
        - Top 5 chunks with relevance scores
        - Citation-enforced prompt
        """
    )
    st.divider()

    selected_model = st.selectbox(
        "LLM Model",
        AVAILABLE_MODELS,
        index=0,
        help="Switch between locally available Ollama models",
    )

    st.divider()

    # ── AGENTIC AI — Mode selector ────────────────────────────────────────────
    # Standard RAG:  fixed pipeline  →  retrieve once  →  generate answer
    # Agentic Mode:  reasoning loop  →  agent decides which tools to call,
    #                how many times, and in what order  →  final answer
    # The toggle value is stored in session_state so it persists across reruns.
    st.subheader("Mode")
    selected_mode = st.radio(
        label="Pipeline mode",
        options=["Standard RAG", "Agentic Mode"],
        index=0,
        help=(
            "Standard RAG: one retrieval pass, one generation.\n\n"
            "Agentic Mode: the LLM decides which tools to call and can "
            "search multiple times before giving a final answer."
        ),
        label_visibility="collapsed",
    )
    if selected_mode == "Agentic Mode":
        st.caption(
            "Agent tools: `rewrite_query` · `search_papers` · `get_paper_summary`"
        )
    # ── END AGENTIC AI — Mode selector ────────────────────────────────────────

    st.divider()
    if st.button("Clear conversation"):
        st.session_state.messages = []
        st.rerun()

# ── Load retriever once (heavy — shared across all models) ────────────────────

@st.cache_resource(show_spinner="Loading retriever models — please wait...")
def load_retriever():
    return build_retriever()

retriever = load_retriever()

# ── Build chain for selected model (cached per model name) ────────────────────

@st.cache_resource(show_spinner="Loading LLM...")
def load_chain(model_name: str):
    llm = ChatOllama(model=model_name, temperature=0, base_url=OLLAMA_HOST)
    chain = (
        {
            "context":  retriever | RunnableLambda(format_docs_with_citations),
            "question": RunnablePassthrough(),
        }
        | CITATION_PROMPT
        | llm
        | StrOutputParser()
    )
    return chain

chain = load_chain(selected_model)

# ── Chat state ────────────────────────────────────────────────────────────────

if "messages" not in st.session_state:
    st.session_state.messages = []

# Show which model is active
st.info(f"Active model: **{selected_model}**")

# Render conversation history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg["role"] == "assistant":
            if "model" in msg:
                st.caption(f"Generated by: `{msg['model']}`")
            if "sources" in msg:
                with st.expander("Retrieved sources"):
                    for i, s in enumerate(msg["sources"], 1):
                        score_label = f"  —  relevance: `{s['relevance_score']:.4f}`" if s.get("relevance_score") is not None else ""
                        st.caption(f"**[{i}]** {s['url']}{score_label}")
                        st.markdown(f"> {s['snippet']}...")
                        if i < len(msg["sources"]):
                            st.divider()

# ── Chat input ────────────────────────────────────────────────────────────────

if question := st.chat_input("Ask anything about the research paper..."):

    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)


    with st.chat_message("assistant"):

        # ── AGENTIC AI — branch on selected mode ─────────────────────────────
        if selected_mode == "Agentic Mode":
            # ── AGENTIC AI: run the reasoning loop instead of the fixed chain ──
            # run_agent() (defined in agent.py) returns:
            #   • "answer" — the final answer text
            #   • "steps"  — list of tool calls the agent made (for the trace panel)
            with st.spinner(f"Agent reasoning with {selected_model}..."):
                result = run_agent(
                    question=question,
                    model_name=selected_model,
                    retriever=retriever,
                )
            answer = result["answer"]
            agent_steps = result["steps"]

            # Terminal logging
            print("\n" + "="*60)
            print(f"[AGENTIC] QUESTION : {question}")
            print(f"[AGENTIC] MODEL    : {selected_model}")
            print(f"[AGENTIC] STEPS    : {agent_steps}")
            print(f"[AGENTIC] ANSWER   : {answer}")
            print("="*60 + "\n")

            st.markdown(answer)
            st.caption(f"Generated by: `{selected_model}` · **Agentic Mode**")

            # AGENTIC AI — show the reasoning trace so you can see what the
            # agent decided to do (which tools it called, with what queries)
            if agent_steps:
                with st.expander("Agent reasoning trace"):
                    for i, step in enumerate(agent_steps, 1):
                        st.markdown(f"**Step {i}:** {step}")

            sources = []  # agentic mode doesn't expose raw docs directly

        else:
            # ── Standard RAG: original fixed pipeline (unchanged) ─────────────
            with st.spinner(f"Retrieving and generating with {selected_model}..."):
                retrieved_docs = retriever.invoke(question)
                answer = chain.invoke(question)

            # Terminal logging
            print("\n" + "="*60)
            print(f"QUESTION : {question}")
            print(f"MODEL    : {selected_model}")
            print("-"*60)
            for i, doc in enumerate(retrieved_docs, 1):
                score = doc.metadata.get("relevance_score", "n/a")
                print(f"[{i}] score={score}  source={doc.metadata.get('source','unknown')}")
                print(f"    {doc.page_content.strip()[:200]}")
            print("-"*60)
            print(f"ANSWER   : {answer}")
            print("="*60 + "\n")

            st.markdown(answer)
            st.caption(f"Generated by: `{selected_model}`")

            sources = []
            with st.expander("Retrieved sources"):
                for i, doc in enumerate(retrieved_docs, 1):
                    url       = doc.metadata.get("source", "unknown")
                    snippet   = doc.page_content.strip()[:250]
                    relevance = doc.metadata.get("relevance_score")
                    sources.append({"url": url, "snippet": snippet, "relevance_score": relevance})

                    score_label = f"  —  relevance: `{relevance:.4f}`" if relevance is not None else ""
                    st.caption(f"**[{i}]** {url}{score_label}")
                    st.markdown(f"> {snippet}...")
                    if i < len(retrieved_docs):
                        st.divider()
        # ── END AGENTIC AI — branch ───────────────────────────────────────────

    st.session_state.messages.append({
        "role":    "assistant",
        "content": answer,
        "model":   selected_model,
        "sources": sources,
    })
